### ISSUE TITLE
callback functions not working

### ISSUE THREAD

**Issue by rolandlo** [baf57/Xournalpp_FlyPie#1]
Hi! 

Xournal++ dev here. I took a look at your plugin, which looks like a very nice addition to Xournal++. Great work! However the callback functions are not working, it seems to me. 

First of all, in 9852b004b0b294bd73c982ccf38b6db0f630db64 you made the callback functions `local`. They are not found in `initUi` any more. This is easy to fix (just remove the `local` keyword again).

Secondly the callback functions use a parameter `Pass`. A global variable `Pass` is defined in `initUi`, but it is not really passed to the callback, when it is executed. Instead `Pass` is always `3`, the last value it got in `initUi`. 
To fix the second problem, I have created a PR, that allows passing an integer parameter to the callback function, see https://github.com/xournalpp/xournalpp/pull/4185
With the PR we can simply pass `aind` via `["mode"] = aind` in https://github.com/baf57/Xournalpp_FlyPie/blob/9852b004b0b294bd73c982ccf38b6db0f630db64/src/main.lua#L18-L19
Then things work as expected.

Unrelated to that I noticed two more small problems:
1. The shortcuts for the eraser modes "Whiteout" and "Delete stroke" are interchanged. This can easily be changed in FlyPie.
2. Choosing the light green color (that uses the shortcut Control+Shift+Alt+R starts the recorder (on Ubuntu 22.04). That needs a bit more work.

**Comment by baf57** [comment]
Hi @rolandlo thanks for the info on the callbacks! I will implement these this weekend just to make sure that the whole thing still works as expected.

I ended up not really using this FlyPie plugin much because I was having some issues with accurately selecting radial menu options with my pen because of Wayland's somewhat lackluster hand-rejection on touchscreens. Realistically I just need to buy one of those drawing tablet gloves, but I digress.

As for your last two points you brought up, I will swap those modes, and also I will remove that shortcut possibility from the set of possible shortcuts. I use Debian with either i3 or Gnome, so there aren't _too many_ button combos I had to watch out for there, so it's good that you pointed this out.

**Comment by rolandlo** [comment]
PR https://github.com/xournalpp/xournalpp/pull/4185 has now been merged, so fixing the callback issue should be easy now.

By the way, on the readme, you advise to copy the plugin into the system folder
`/usr/share/xournalpp/plugins/FlyPie/`. This is not needed on the latest development version. 
Plugins are also loaded from the config folder, i.e. the user should copy the files to `~/.config/xournalpp/plugins/FlyPie`

**Comment by baf57** [comment]
I am going to make a branch which is aligned with the xournalpp nightly, and then once your feature is pulled into stable I will merge my branches.

As for the color issue above... well to fix it properly will require a lot of work (ie. skipping over Ctrl+Shift+Alt+r and then having to remap everything which is assigned after that color callback assignment... which is most things). I'm thinking I could just make it so that when the Ctrl+Shift+Alt+r combo would be encountered I just instead assign it to some other currently unused value, however this feels a little janky to me.

**Comment by baf57** [comment]
I have created the branch [xournalpp-nightly-cb-fix](/baf57/Xournalpp_FlyPie/tree/xournalpp-nightly-cb-fix) to fix the core issue being mentioned here.

As for the other minor issues, all of those have been fixed in the main branch.

Thanks again @rolandlo
